# Generated by Django 3.2.25 on 2024-08-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-replied', '-created_on'],
            },
        ),
    ]
