# Generated by Django 3.2.25 on 2024-06-08 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('friendly_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quality', models.CharField(choices=[('new', 'New'), ('used_like_new', 'Used - Like New'), ('used_perfect', 'Used - Perfect'), ('used_good', 'Used - Good'), ('used_very_used', 'Used - Very Used')], default='used_good', max_length=50)),
                ('age', models.CharField(choices=[('newbor_infant', 'Newborn & Infant'), ('toodler', 'Toddler'), ('preschooler', 'Preschooler'), ('schooler', 'Schooler')], default='newborn_infant', max_length=50)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/books/placeholder.placeholder.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='media/books')),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('declaim', 'DECLAIM'), ('eshop', 'E-SHOP'), ('sold', 'SOLD'), ('paid', 'PAID')], default='open', max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toy_category', to='toys.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toy_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on', 'status'],
            },
        ),
    ]
