# Generated by Django 3.2.25 on 2024-06-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='toys',
            options={'ordering': ['-created_on', 'status'], 'verbose_name_plural': 'Toys'},
        ),
    ]
