# Generated by Django 3.2.25 on 2024-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20240807_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
