# Generated by Django 3.2.25 on 2024-06-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20240608_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='category',
            field=models.ForeignKey(blank=True, default='toys', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toy_category', to='toys.category'),
        ),
        migrations.AlterField(
            model_name='toys',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toys',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
