# Generated by Django 3.2.25 on 2024-06-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('toys', '0005_alter_toys_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sells', to='profiles.userprofile'),
        ),
    ]
