# Generated by Django 3.2.25 on 2024-07-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('toys', '0007_auto_20240628_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toys',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='toys',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sells', to='profiles.userprofile'),
        ),
    ]
